version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "23:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: fast-check
    versions:
    - 2.12.1
    - 2.12.2
    - 2.13.0
